// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Giraffe.HotReload.Cli")>]
[<assembly: AssemblyProductAttribute("Giraffe.HotReload")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2019-04-25T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","9e9f68b6f83a774ccf5fe3a0a224c59dc99c0a70")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Giraffe.HotReload.Cli"
    let [<Literal>] AssemblyProduct = "Giraffe.HotReload"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2019-04-25T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.4.0"
    let [<Literal>] AssemblyInformationalVersion = "0.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "9e9f68b6f83a774ccf5fe3a0a224c59dc99c0a70"
